name: "ll_project"
type: "python:3.10"
build:
  flavor: none

relationships:
  database: "db:postgresql"

# 應用程序被暴露到網上時使用的配置
web:
  upstream:
    socket_family: unix
  commands:
    start: "cd /app/ll_project && gunicorn -w 4 -b unix:$PLATFORM_APP_SOCKET ll_project.wsgi:application"

  locations:
    "/":
      passthru: true
    "/static":
      root: "static"
      expires: 1h
      allow: true

# 應用程序的永久性磁盤的大小（單位為 MB）
disk: 512

# 設置用於讀寫日志的本地掛載
mounts:
 "logs":
   source: local
   source_path: logs
# 在應用程序生命周期的不同時間點執行的鉤子（hook）
hooks:
  build: |
   pip install --upgrade pip
   pip install -r requirements.txt
   pip install -r requirements_remote.txt

   mkdir logs
   python manage.py collectstatic
   rm -rf logs

  deploy: |
   python manage.py migrate
